Repository googleinterns/step191-2020, pull requests merged in 2020-08, with the labels that each got.

#105 Links main screen & restructure File tree
  src/main/webapp/index.html
  src/main/webapp/style.css
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.html
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
  src/main/webapp/teacher/newGameInstance/newGameInstance.css
  src/main/webapp/teacher/newGameInstance/newGameInstance.html
  src/main/webapp/teacher/newGameInstance/newGameInstance.js
Labels: enhancement, refactoring

#107 Refactor control game instance
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
Labels: refactoring

#112 Verify user in firestore
  src/main/java/com/google/sps/daos/DatabaseUserDao.java
  src/main/java/com/google/sps/daos/UserDao.java
  src/main/java/com/google/sps/servlets/UserServlet.java
  src/main/java/com/google/sps/util/QuizzyContextListener.java
  src/main/webapp/scripts/auth.js
  src/main/webapp/student/play-game.html
Labels: enhancement

#116 Count students registered in game
  pom.xml
  src/main/java/com/google/sps/daos/DatabaseGameDao.java
  src/main/java/com/google/sps/daos/DatabaseGameInstanceDao.java
  src/main/java/com/google/sps/daos/DatabaseUserDao.java
  src/main/java/com/google/sps/daos/GameInstanceDao.java
  src/main/java/com/google/sps/daos/UserDao.java
  src/main/java/com/google/sps/data/GameInstance.java
  src/main/java/com/google/sps/servlets/AnswerQuestionServlet.java
  src/main/java/com/google/sps/servlets/CreateGameInstanceServlet.java
  src/main/java/com/google/sps/servlets/JoinGameInstanceServlet.java
  src/main/java/com/google/sps/servlets/UserServlet.java
  src/main/java/com/google/sps/util/QuizzyContextListener.java
  src/main/webapp/student/enter-game.html
  src/main/webapp/student/play-game.html
  src/main/webapp/student/scripts/enter-game.js
  src/main/webapp/student/scripts/play-game.js
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.html
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
  src/main/webapp/teacher/newGameInstance/newGameInstance.js
  src/test/java/com/google/sps/CreateGameInstanceServletTest.java
  src/test/java/com/google/sps/NextQuestionServletTest.java
Labels: enhancement, refactoring

#126 Teacher history stats
  src/main/java/com/google/sps/servlets/AnswerQuestionServlet.java
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.css
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.html
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
Labels: enhancement

#133 Add User servlet test
  src/main/java/com/google/sps/servlets/UserServlet.java
  src/test/java/com/google/sps/UserServletTest.java
Labels: test

#138 Init game instance all data
  src/main/java/com/google/sps/daos/DatabaseGameDao.java
  src/main/java/com/google/sps/daos/DatabaseGameInstanceDao.java
  src/main/java/com/google/sps/daos/GameInstanceDao.java
  src/main/java/com/google/sps/data/Answer.java
  src/main/java/com/google/sps/data/Question.java
  src/main/java/com/google/sps/servlets/CreateGameInstanceServlet.java
  src/test/java/com/google/sps/CreateGameInstanceServletTest.java
Labels: bug

#139 Animal alias
  src/main/java/com/google/sps/daos/DatabaseUserDao.java
  src/main/webapp/student/play-game.html
  src/main/webapp/student/scripts/play-game.js
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
Labels: enhancement

#140 Show data and update it correctly
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
Labels: bug

#137 Control Game Instance Styling
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.css
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.html
  src/main/webapp/teacher/controlGameInstance/controlGameInstance.js
Labels: enhancement
